// Content for Settings → User Guide. Screenshots live in /public/guide (data in them is blurred).
// icon = lucide-react icon name, resolved in UserGuide.jsx.

export const GUIDE_GROUPS = [
  { id: "start", label: "Getting Started", color: "indigo" },
  { id: "orders", label: "Orders & Dispatch", color: "violet" },
  { id: "inventory", label: "Inventory", color: "emerald" },
  { id: "contracts", label: "Contracts & Billing", color: "amber" },
  { id: "masters", label: "Masters", color: "sky" },
  { id: "work", label: "Tasks, Email & Reports", color: "rose" },
  { id: "admin", label: "Settings & Access", color: "slate" },
];

export const GUIDES = [
  {
    id: "dashboard", group: "start", icon: "LayoutDashboard", title: "Dashboard",
    summary: "A one-glance view of the business: today's activity, stock, payments, charts and your widgets.",
    images: [{ src: "dashboard", caption: "Top cards, Stock Health, Sales and Godown charts" }],
    steps: [
      { t: "Open the Dashboard", d: "Click Dashboard in the left menu. Use the filters at the top (Overall / Today / Financial Year / Category) to change the period." },
      { t: "Read the top cards", d: "Orders, Dispatched, Returns, Stock In and Damaged show today's counts. Stock Available, Due Payments, Pending Bill and Total Order show the current picture." },
      { t: "Jump into a module", d: "Click any card to go straight to that module with the matching data." },
      { t: "Check the charts", d: "Stock Health lists models running low (below 3 units). Sales shows revenue month by month. Godown Stock and Top 10 by Category show where stock sits." },
      { t: "Use the widgets at the bottom", d: "My Tasks, Mail Inbox and Contract Groups give quick access without leaving the Dashboard." },
    ],
    tips: ["Which cards, charts and widgets each user sees is controlled in Settings → Manage Roles → Dashboard Widgets, or per user through Custom Access."],
    permission: "Each Dashboard section has its own permission (Dashboard Widgets group).",
  },
  {
    id: "orders", group: "orders", icon: "ShoppingCart", title: "Order Processing",
    summary: "All orders in one place: Draft, Active, Returned, On Hold, Completed and Cancelled.",
    images: [{ src: "orders", caption: "Order list with status tabs, search and filters" }],
    steps: [
      { t: "Open the order list", d: "Go to Order Processing → Order Processing. The tabs at the top (Draft, Active, Returned, On Hold, Completed, Cancelled) show how many orders are in each state." },
      { t: "Find an order", d: "Search by Order ID or GEMC no. Narrow the list with the status, time, delivery platform and platform filters." },
      { t: "Open Order Details", d: "Click an order. A full page opens with details, payment, GeM and contact info, order items, history, returns and serial replacements." },
      { t: "Work with draft orders", d: "In a draft order pick the serial numbers for each item and press Save Draft to keep your picks. Confirm the order only when everything is correct." },
      { t: "Save your edits", d: "After changing anything inside Order Details, use the Save bar at the bottom of the page." },
      { t: "Come back to the list", d: "Use the Back button on the page or in your browser; you return to the same list and filters." },
    ],
    tips: ["Use the Columns button to show or hide table columns.", "Order status appears as a coloured badge next to the Order ID in Order Details."],
    permission: "Needs the Orders permission; editing uses the Edit Rights set in the role.",
  },
  {
    id: "new-dispatch", group: "orders", icon: "Truck", title: "New Dispatch",
    summary: "Create a dispatch: choose the order, scan serial numbers and fill in courier details.",
    images: [{ src: "new-dispatch", caption: "New Dispatch form" }],
    steps: [
      { t: "Open the form", d: "Go to Order Processing → New Dispatch." },
      { t: "Choose the order", d: "Select the order or client you are shipping for." },
      { t: "Add items and serials", d: "Scan or select serial numbers for each item. Non-serialised items need a quantity instead." },
      { t: "Fill platform fields", d: "Custom fields created for the platform in Settings → Platform Master appear in the form. Required ones are marked with *." },
      { t: "Save", d: "Save the dispatch. It now appears in the Dispatch list." },
    ],
    tips: ["A required field left empty blocks saving; the field is highlighted."],
    permission: "Needs the Dispatch permission.",
  },
  {
    id: "dispatch", group: "orders", icon: "Package", title: "Dispatch",
    summary: "Every shipped dispatch with tracking and POD (proof of delivery).",
    images: [{ src: "dispatch", caption: "Dispatch list with courier filter" }],
    steps: [
      { t: "Open the list", d: "Go to Order Processing → Dispatch." },
      { t: "Filter", d: "Filter by delivery platform (courier) or status and use the search box." },
      { t: "Open a dispatch", d: "Click a row to see tracking, items and serials." },
      { t: "Upload POD", d: "Attach the proof of delivery. You may also enter a Delivered Date; it is optional." },
    ],
    tips: ["If Delivered Date is left empty the system uses its default behaviour."],
    permission: "Needs the Dispatch permission.",
  },
  {
    id: "returns-damaged", group: "orders", icon: "RotateCcw", title: "Returns & Damaged",
    summary: "Track items that came back or were found damaged.",
    images: [{ src: "returns", caption: "Returns list" }, { src: "damaged", caption: "Damaged items list" }],
    steps: [
      { t: "Choose the list", d: "Open Returns & Damaged in the left menu and pick Returns or Damaged." },
      { t: "Search", d: "Search by order, serial number or item." },
      { t: "Review history", d: "The same return records also appear in the Return History section inside Order Details." },
    ],
    tips: [],
    permission: "Needs the Returns / Damaged permissions.",
  },
  {
    id: "stock-in", group: "inventory", icon: "PackagePlus", title: "Stock In",
    summary: "Add new stock from a vendor invoice, keep drafts and revert mistakes safely.",
    images: [{ src: "stock-in-new", caption: "New Stock In: invoice details and barcode scan" }, { src: "stock-in", caption: "Stock In lists" }],
    steps: [
      { t: "Start a Stock In", d: "Open Inventory → Stock In and stay on the New Stock In tab." },
      { t: "Enter invoice details", d: "Select the Vendor, type the Invoice No. and Invoice Date. You can attach the invoice file or use Auto-Fill from Invoice (Excel/PDF)." },
      { t: "Scan items", d: "Scan the barcode and press Enter (Alt+B jumps to the scan box) or use Search by Name. Each item appears in the grid." },
      { t: "Save as draft or finalize", d: "Drafts can be finished later from the Drafts tab. Stock is added only when you finalize." },
      { t: "Fix a mistake", d: "Open the entry under Finalized and use Revert. Stock counts correct themselves." },
    ],
    tips: ["Revert and Delete are separate permissions.",],
    permission: "Needs the Stock In permission.",
  },
  {
    id: "current-stock", group: "inventory", icon: "Boxes", title: "Current Stock",
    summary: "What is available right now, by item, godown and serial number.",
    images: [{ src: "current-stock", caption: "Current stock list" }],
    steps: [
      { t: "Open Current Stock", d: "Go to Inventory → Current Stock." },
      { t: "Filter", d: "Use category, brand and godown filters, or search by item name or serial." },
      { t: "See serials", d: "Click a serialised item to list every available serial number." },
    ],
    tips: [],
    permission: "Needs the Current Stock permission.",
  },
  {
    id: "godown-transfer", group: "inventory", icon: "ArrowLeftRight", title: "Godown Transfer",
    summary: "Move stock from one godown (location) to another.",
    images: [{ src: "godown-transfer", caption: "Godown transfer" }],
    steps: [
      { t: "Open the page", d: "Go to Inventory → Godown Transfer." },
      { t: "Pick source and destination", d: "Choose the godown you are moving from and the one you are moving to." },
      { t: "Select items", d: "Select the items and quantities, then confirm the transfer." },
    ],
    tips: ["Check Current Stock afterwards to confirm both godowns."],
    permission: "Needs the Godown Transfer permission.",
  },
  {
    id: "item-master", group: "inventory", icon: "Layers", title: "Item Master & Variants",
    summary: "Create items and manage their variants (models) and serial numbers.",
    images: [{ src: "item-master", caption: "Item Master" }],
    steps: [
      { t: "Add an item", d: "In Masters → Item Master choose Category and Brand, enter the Item Name (and optional codes), then Save Item." },
      { t: "Set serial tracking", d: "Set 'Ask Serial No.' to Yes for items that have serial numbers." },
      { t: "Manage variants", d: "Open Item Variant to create models for the item." },
      { t: "Add serials", d: "Use the '#' button on a variant. A full page opens where serials can be added." },
    ],
    tips: ["Filter the list by category or by serialised / non-serialised."],
    permission: "Needs the Item Master / Item Variant permissions.",
  },
  {
    id: "contracts", group: "contracts", icon: "FileText", title: "Contracts",
    summary: "Upload contracts (one or many), review each file and search saved contracts.",
    images: [{ src: "contracts", caption: "Saved Contracts" }, { src: "contracts-upload", caption: "Contract upload" }],
    steps: [
      { t: "Upload", d: "Go to Contracts → Upload and add one or more contract files together." },
      { t: "Review each file", d: "Check the extracted details for every file, correct anything wrong, then save." },
      { t: "Search saved contracts", d: "Open Contracts → Saved Contracts and search by contract no., buyer or GSTIN." },
      { t: "Track status", d: "A contract's status follows the status of its order." },
    ],
    tips: [],
    permission: "Needs the Contracts permission.",
  },
  {
    id: "contract-groups", group: "contracts", icon: "Layers", title: "Contract Groups",
    summary: "Group contracts of the same buyer and see a DGGI-sheet style summary with commission.",
    images: [{ src: "contract-groups", caption: "Contract Groups list" }],
    steps: [
      { t: "Create a group", d: "Open Contracts → Contract Groups and create a group by choosing a combination of address, GSTIN, email, department, organisation or ministry." },
      { t: "Add contracts", d: "The system suggests contracts that match; add the ones you want." },
      { t: "Open the group", d: "Click a group to see the 18-column table (Landing price, Delivered, Short, amounts and Commission)." },
      { t: "Edit inline", d: "Commission value and Commission Status (Paid / Unpaid / Pending) are edited directly in the table." },
      { t: "Remove or delete", d: "Removing a contract or deleting a group never changes your orders or contract data." },
    ],
    tips: ["New contracts are never added to a group automatically.", "The Commission Status list is a master you can extend."],
    permission: "Needs the Contract Groups permission.",
  },
  {
    id: "billing", group: "contracts", icon: "Receipt", title: "Billing",
    summary: "Invoices, payments and pending bills.",
    images: [{ src: "billing", caption: "Billing" }],
    steps: [
      { t: "Open Billing", d: "Click Billing in the left menu." },
      { t: "Find an invoice", d: "Use search and filters." },
      { t: "Update payment", d: "Record or change payment status from the row." },
    ],
    tips: [],
    permission: "Needs the Billing permission.",
  },
  {
    id: "clients", group: "masters", icon: "Users", title: "Client Master",
    summary: "Your clients (buyers). Create and edit on a full page.",
    images: [{ src: "clients", caption: "Client list" }, { src: "clients-new", caption: "New client page" }],
    steps: [
      { t: "Open the list", d: "Go to Masters → Client Master." },
      { t: "Add or edit", d: "Click Add Client or the edit icon. The form opens on its own page." },
      { t: "Save", d: "Fill the details and Save. Cancel returns to the list." },
    ],
    tips: ["Clients are only ever created manually."],
    permission: "Needs the Client Master permission.",
  },
  {
    id: "companies", group: "masters", icon: "Building2", title: "Company Master",
    summary: "Your own companies; the company switcher in the top bar comes from here.",
    images: [{ src: "companies", caption: "Company list" }, { src: "companies-new", caption: "New company page" }],
    steps: [
      { t: "Open the list", d: "Go to Settings → Company Master." },
      { t: "Create or edit", d: "Open the full page and fill in GST, address and platform details." },
      { t: "Assign users", d: "Choose which companies each user can work in from Settings → Users." },
    ],
    tips: [],
    permission: "Needs the Company Master permission.",
  },
  {
    id: "tasks", group: "work", icon: "CheckSquare", title: "Tasks",
    summary: "Assign work, set due dates and get reminders.",
    images: [{ src: "tasks", caption: "Tasks" }, { src: "daily-tasks", caption: "Daily tasks" }],
    steps: [
      { t: "Create a task", d: "Open Tasks and add a title, assignee and due date." },
      { t: "Get reminded", d: "Tasks that are due soon show a notification toast and appear in the bell." },
      { t: "Track them", d: "Your open tasks also appear in the My Tasks widget on the Dashboard." },
    ],
    tips: [],
    permission: "Needs the Tasks permission.",
  },
  {
    id: "warranty-installations", group: "work", icon: "Wrench", title: "Warranty & Installations",
    summary: "Warranty certificates and installation tracking.",
    images: [{ src: "warranty", caption: "Warranty certificates" }, { src: "installations", caption: "Installations" }],
    steps: [
      { t: "Warranty", d: "Open Warranty Certs to view warranty certificates." },
      { t: "Installations", d: "Open Installations to track installations." },
    ],
    tips: ["Email wording is controlled in Settings → Email Templates."],
    permission: "Needs the Warranty / Installations permissions.",
  },
  {
    id: "reports", group: "work", icon: "BarChart3", title: "Reports",
    summary: "Business reports and exports.",
    images: [{ src: "reports", caption: "Reports" }],
    steps: [
      { t: "Open Reports", d: "Go to Settings → Reports." },
      { t: "Choose a report", d: "Pick the report and set the filters you need." },
    ],
    tips: [],
    permission: "Needs the Reports permission.",
  },
  {
    id: "email-templates", group: "work", icon: "Mail", title: "Email Templates",
    summary: "Templates for the emails sent to customers.",
    images: [{ src: "email-templates", caption: "Email Templates" }],
    steps: [
      { t: "Open the page", d: "Go to Settings → Email → Email Templates." },
      { t: "Pick or create", d: "Choose an existing template or create a new one." },
      { t: "Insert variables", d: "Use the variable picker to insert values such as order date or invoice no." },
    ],
    tips: ["Sent emails can be reviewed under Order Details → email history."],
    permission: "Needs the Email Templates permission.",
  },
  {
    id: "platform-master", group: "admin", icon: "Settings2", title: "Platform Master",
    summary: "Platforms (GeM, Amazon, …) and their custom fields.",
    images: [{ src: "platform-master", caption: "Platform Master" }],
    steps: [
      { t: "Open the page", d: "Go to Settings → Master → Platform Master." },
      { t: "Manage fields", d: "Use Manage Fields on a platform to add, edit or remove custom fields." },
      { t: "Use them", d: "These fields show in New Dispatch for that platform." },
    ],
    tips: ["Managing fields and editing model pricing / packaging are separate permissions."],
    permission: "Needs the Platform Master permission.",
  },
  {
    id: "users", group: "admin", icon: "UserCog", title: "Users",
    summary: "Create users and decide their role, companies and extra access.",
    images: [{ src: "users", caption: "Users" }, { src: "users-new", caption: "New user page" }],
    steps: [
      { t: "Add a user", d: "Open Settings → User → Users and click Add User." },
      { t: "Choose a role", d: "The user receives that role's permissions." },
      { t: "Custom Access", d: "Allow or block individual permissions for just this user. 'Allow all' and 'Block all' switch everything quickly." },
      { t: "Assign companies", d: "Choose which companies the user can work in." },
    ],
    tips: ["Custom Access overrides are saved per user; the role itself is not changed."],
    permission: "Needs the Users permission.",
  },
  {
    id: "roles", group: "admin", icon: "ShieldCheck", title: "Roles & Permissions",
    summary: "Decide what each role can see and edit.",
    images: [{ src: "roles", caption: "Roles" }, { src: "roles-detail", caption: "Permissions page" }],
    steps: [
      { t: "Open Manage Roles", d: "Go to Settings → User → Manage Roles." },
      { t: "Open permissions", d: "Click the key button next to a role. A full page opens." },
      { t: "View Access", d: "Tick which pages and Dashboard sections the role may see." },
      { t: "Edit Rights", d: "Tick which edit, delete and revert actions are allowed." },
      { t: "Search and save", d: "Use the search box to find a permission quickly, then Save." },
    ],
    tips: ["Dashboard cards, charts and widgets are in the 'Dashboard Widgets' group."],
    permission: "Needs the Roles permission.",
  },
  {
    id: "user-activity", group: "admin", icon: "Activity", title: "User Activity",
    summary: "See who did what and when.",
    images: [{ src: "user-activity", caption: "User Activity log" }],
    steps: [
      { t: "Open the log", d: "Go to Settings → User → User Activity." },
      { t: "Review", d: "Browse the log to see recent actions by your users." },
    ],
    tips: [],
    permission: "Needs the User Activity permission.",
  },
];
